ALTER TABLE EMPLOYEE_TBL
ADD RATING NUMBER CHECK ( RATING BETWEEN 0 AND 100);

ALTER TABLE EMPLOYEE_TBL
ADD SSN VARCHAR2(20) DEFAULT 'XXX-XX-XXXX' NOT NULL;

ALTER TABLE READER_TBL
ADD SSN VARCHAR2(20) default 'XXX-XX-XXXX' NOT NULL;

ALTER TABLE BOOK_TBL
MODIFY TITLE NOT NULL;

ALTER TABLE AUTHOR_TBL
MODIFY LAST_NAME VARCHAR2(30);

ALTER TABLE READER_TBL
MODIFY LAST_NAME VARCHAR2(30);

ALTER TABLE EMPLOYEE_TBL
MODIFY LAST_NAME VARCHAR2(30);