-- 1.a
SELECT * FROM EMPLOYEE_TBL
ORDER BY LAST_NAME, FIRST_NAME;

-- 1.b
SELECT * FROM READER_TBL
ORDER BY LAST_NAME, FIRST_NAME;

-- 1.c
SELECT * FROM AUTHOR_TBL
ORDER BY LAST_NAME, FIRST_NAME;

-- 2.a
SELECT B.BOOK_ID, B.TITLE, AVG(C.GROSS_PRICE) AS AVERAGE_PRICE FROM BOOK_TBL B
LEFT JOIN COPY_TBL C ON B.BOOK_ID = C.BOOK_ID
GROUP BY B.BOOK_ID, B.TITLE;

-- 2.b
SELECT B.BOOK_ID, B.TITLE, SUM(C.GROSS_PRICE) AS TOTAL_PRICE FROM BOOK_TBL B
LEFT JOIN COPY_TBL C ON B.BOOK_ID = C.BOOK_ID
GROUP BY B.BOOK_ID, B.TITLE;

-- 2.c
SELECT B.BOOK_ID, B.TITLE, SUM(C.COPY_ID) AS COPIES_COUNT FROM BOOK_TBL B
LEFT JOIN COPY_TBL C ON B.BOOK_ID = C.BOOK_ID
GROUP BY B.BOOK_ID, B.TITLE;

-- 3.a
SELECT B.TITLE, A.FIRST_NAME, A.LAST_NAME, AB.AUTHOR_SHARE FROM BOOK_TBL B
LEFT JOIN AUTHOR_BOOK_TBL AB ON B.BOOK_ID = AB.BOOK_ID
LEFT JOIN AUTHOR_TBL A ON AB.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.TITLE, A.FIRST_NAME, A.LAST_NAME, AB.AUTHOR_SHARE
ORDER BY B.TITLE;

-- 3.b
SELECT I.INVOICE_ID, I.ISSUE_DATE, I.INVOICE_NUMBER, SUM(C.COPY_ID) AS COPIES_COUNT, SUM(C.GROSS_PRICE) AS TOTAL_PRICE
FROM INVOICE_TBL I
LEFT JOIN COPY_TBL C ON I.INVOICE_ID = C.INVOICE_ID
GROUP BY I.INVOICE_ID, I.ISSUE_DATE, I.INVOICE_NUMBER;

-- 3.c
SELECT P.PUBLISHER_NAME, B.TITLE FROM PUBLISHER_TBL P
JOIN BOOK_TBL B ON P.PUBLISHER_ID = B.PUBLISHER_ID;

-- 4.a
SELECT B.* FROM BOOK_TBL B
LEFT JOIN AUTHOR_BOOK_TBL AB ON B.BOOK_ID = AB.BOOK_ID
LEFT JOIN AUTHOR_TBL A ON AB.AUTHOR_ID = A.AUTHOR_ID
WHERE A.FIRST_NAME = 'Mark' AND A.LAST_NAME = 'Twain';

-- 4.b
SELECT C.COPY_ID, B.TITLE, C.GROSS_PRICE, C.VAT FROM COPY_TBL C
LEFT JOIN BOOK_TBL B ON C.BOOK_ID = B.BOOK_ID
RIGHT JOIN INVOICE_TBL I ON C.INVOICE_ID = I.INVOICE_ID
WHERE I.INVOICE_NUMBER = 'INV001';

-- 4.c
SELECT B.BOOK_ID, B.TITLE, B.PUBLICATION_YEAR FROM BOOK_TBL B
RIGHT JOIN PUBLISHER_TBL P ON B.PUBLISHER_ID = P.PUBLISHER_ID
WHERE P.PUBLISHER_NAME = 'Penguin Books';

-- 5.a
SELECT B.TITLE, SUM(C.COPY_ID) AS COPIES_COUNT FROM BOOK_TBL B
LEFT JOIN COPY_TBL C ON B.BOOK_ID = C.BOOK_ID
WHERE TITLE = 'Mystery of the Ancients'
GROUP BY B.TITLE;

-- 5.b
SELECT P.PUBLISHER_NAME, SUM(I.INVOICE_ID) AS INVOICES_COUNT FROM PUBLISHER_TBL P
LEFT JOIN INVOICE_TBL I ON P.PUBLISHER_ID = I.PUBLISHER_ID
WHERE P.PUBLISHER_NAME = 'Penguin Books'
GROUP BY P.PUBLISHER_NAME;

-- 5.c
SELECT R.FIRST_NAME, R.LAST_NAME FROM READER_TBL R
LEFT JOIN RENTAL_TBL RE ON R.READER_ID = RE.READER_ID
LEFT JOIN COPY_TBL C ON RE.COPY_ID = C.COPY_ID
WHERE C.COPY_ID = 4;

-- 6.a
SELECT A.* FROM AUTHOR_TBL A
LEFT JOIN AUTHOR_BOOK_TBL AB ON A.AUTHOR_ID = AB.AUTHOR_ID
GROUP BY A.AUTHOR_ID, FIRST_NAME, LAST_NAME
HAVING SUM(AB.BOOK_ID) > 2;

-- 6.b
SELECT E.FIRST_NAME, E.LAST_NAME FROM EMPLOYEE_TBL E
LEFT JOIN INVOICE_TBL I ON E.EMPLOYEE_ID = I.EMPLOYEE_ID
GROUP BY E.FIRST_NAME, E.LAST_NAME
HAVING SUM(I.INVOICE_ID) > 2;

-- 6.c
SELECT R.FIRST_NAME, R.LAST_NAME FROM READER_TBL R
LEFT JOIN RENTAL_TBL RE ON R.READER_ID = RE.READER_ID
GROUP BY R.FIRST_NAME, R.LAST_NAME
HAVING SUM(RE.RENTAL_ID) >= 2;

-- 7.a
SELECT C.COPY_ID, SUM(R.RENTAL_ID) AS BORROWED_COUNT FROM COPY_TBL C
LEFT JOIN RENTAL_TBL R ON C.COPY_ID = R.COPY_ID
GROUP BY C.COPY_ID;

-- 7.b
SELECT R.FIRST_NAME, R.LAST_NAME, SUM(RE.RENTAL_ID) AS BORROWED_COUNT FROM READER_TBL R
LEFT JOIN RENTAL_TBL RE ON R.READER_ID = RE.READER_ID
GROUP BY R.FIRST_NAME, R.LAST_NAME;

-- 7.c
SELECT E.FIRST_NAME, E.LAST_NAME, SUM(R.RENTAL_ID) AS LENT_COUNT FROM EMPLOYEE_TBL E
LEFT JOIN RENTAL_TBL R ON E.EMPLOYEE_ID = R.EMPLOYEE_ID_RENT
GROUP BY E.FIRST_NAME, E.LAST_NAME;

-- 8.a
SELECT C.COPY_ID, B.TITLE FROM COPY_TBL C
RIGHT JOIN BOOK_TBL B ON C.BOOK_ID = B.BOOK_ID
RIGHT JOIN RENTAL_TBL R ON C.COPY_ID = R.COPY_ID
WHERE R.RETURN_DATE IS NULL;

-- 8.b
SELECT R.FIRST_NAME, R.LAST_NAME FROM READER_TBL R
RIGHT JOIN RENTAL_TBL RE ON R.READER_ID = RE.READER_ID
WHERE RE.RETURN_DATE IS NULL
GROUP BY R.FIRST_NAME, R.LAST_NAME;

-- 8.c
SELECT E.FIRST_NAME, E.LAST_NAME
FROM EMPLOYEE_TBL E
WHERE NOT EXISTS (
    SELECT 1 FROM RENTAL_TBL R
    WHERE E.EMPLOYEE_ID = R.EMPLOYEE_ID_RETURN
);

