-- 1.a
SELECT B.TITLE, R.LAST_NAME, TO_CHAR(RE.RENTAL_DATE, 'DD-MM-YYYY') AS RENTAL_DATE FROM READER_TBL R
LEFT JOIN RENTAL_TBL RE ON R.READER_ID = RE.READER_ID
LEFT JOIN COPY_TBL C ON RE.COPY_ID = C.COPY_ID
LEFT JOIN BOOK_TBL B ON C.BOOK_ID = B.BOOK_ID;

-- 1.b
SELECT B.TITLE, I.INVOICE_NUMBER, TO_CHAR(I.ISSUE_DATE, 'YYYY') AS PURCHASE_YEAR, TO_CHAR(I.ISSUE_DATE, 'MM') AS PURCHASE_MONTH, R.LAST_NAME AS READER_LAST_NAME FROM RENTAL_TBL RE
LEFT JOIN READER_TBL R ON RE.READER_ID = R.READER_ID
LEFT JOIN COPY_TBL C ON RE.COPY_ID = C.COPY_ID
LEFT JOIN BOOK_TBL B ON C.BOOK_ID = B.BOOK_ID
LEFT JOIN INVOICE_TBL I ON C.INVOICE_ID = I.INVOICE_ID;

-- 1.c
SELECT B.TITLE, P.PUBLISHER_NAME, TO_CHAR(RE.RETURN_DATE, 'MM-DD-YYYY') AS RETURN_DATE, E.LAST_NAME AS RENTAL_EMPLOYEE_LAST_NAME FROM RENTAL_TBL RE
LEFT JOIN COPY_TBL C ON RE.COPY_ID = C.COPY_ID
LEFT JOIN BOOK_TBL B ON C.BOOK_ID = B.BOOK_ID
LEFT JOIN PUBLISHER_TBL P ON B.PUBLISHER_ID = P.PUBLISHER_ID
LEFT JOIN EMPLOYEE_TBL E ON RE.EMPLOYEE_ID_RENT = E.EMPLOYEE_ID;

-- 2.a
SELECT
    I.INVOICE_NUMBER,
    I.ISSUE_DATE,
    (
        SELECT LISTAGG(B.TITLE, ', ') WITHIN GROUP (ORDER BY B.TITLE)
        FROM BOOK_TBL B
        WHERE B.BOOK_ID IN (SELECT BOOK_ID FROM COPY_TBL WHERE INVOICE_ID = I.INVOICE_ID)
    ) AS TITLES,
    COUNT(C.COPY_ID) AS COPIES_BOUGHT
FROM
    INVOICE_TBL I
LEFT JOIN
    COPY_TBL C ON I.INVOICE_ID = C.INVOICE_ID
GROUP BY
    I.INVOICE_NUMBER, I.ISSUE_DATE, I.INVOICE_ID;


-- 2.b
SELECT E.LAST_NAME, COUNT(I.INVOICE_ID) AS INVOICE_PROCESSED, (SELECT COUNT(INVOICE_ID) FROM INVOICE_TBL) AS TOTAL_INVOICES FROM EMPLOYEE_TBL E
LEFT JOIN INVOICE_TBL I ON E.EMPLOYEE_ID = I.EMPLOYEE_ID
GROUP BY E.LAST_NAME;

-- 2.c
SELECT P.PUBLISHER_NAME, I.INVOICE_NUMBER, COUNT(C.COPY_ID) FROM INVOICE_TBL I
LEFT JOIN PUBLISHER_TBL P ON I.PUBLISHER_ID = P.PUBLISHER_ID
LEFT JOIN COPY_TBL C ON I.INVOICE_ID = C.INVOICE_ID
GROUP BY P.PUBLISHER_NAME, I.INVOICE_NUMBER;

-- 3.a
SELECT
    B.TITLE,
    SUM(R.RETURN_DATE - R.RENTAL_DATE) AS TOTAL_BORROWED_DAYS
FROM
    BOOK_TBL B
JOIN
    COPY_TBL C ON B.BOOK_ID = C.BOOK_ID
JOIN
    RENTAL_TBL R ON C.COPY_ID = R.COPY_ID
WHERE
    R.RETURN_DATE IS NOT NULL
GROUP BY
    B.TITLE;

-- 3.b
SELECT E.LAST_NAME, NVL(MAX(R.RETURN_DATE), SYSDATE) - MIN(R.RENTAL_DATE) AS BORROWING_DURATION FROM RENTAL_TBL R
JOIN EMPLOYEE_TBL E ON R.EMPLOYEE_ID_RENT = E.EMPLOYEE_ID
GROUP BY E.LAST_NAME, E.EMPLOYEE_ID;

-- 3.c
SELECT
    R.LAST_NAME,
    SUM(RE.RETURN_DATE - RE.RENTAL_DATE) AS TOTAL_DAYS_OF_BORROWING
FROM
    READER_TBL R
JOIN
    RENTAL_TBL RE ON R.READER_ID = RE.READER_ID
WHERE
    RE.RETURN_DATE IS NOT NULL
GROUP BY
    R.LAST_NAME, R.READER_ID;

-- 4.a
SELECT
    TO_CHAR(INVOICE.ISSUE_DATE, 'YYYY-MM') AS MONTH_YEAR,
    PUBLISHER.PUBLISHER_NAME,
    SUM(COPY.GROSS_PRICE + COPY.VAT) AS TOTAL_AMOUNT
FROM
    INVOICE_TBL INVOICE
JOIN
    COPY_TBL COPY ON INVOICE.INVOICE_ID = COPY.INVOICE_ID
JOIN
    BOOK_TBL BOOK ON COPY.BOOK_ID = BOOK.BOOK_ID
JOIN
    PUBLISHER_TBL PUBLISHER ON BOOK.PUBLISHER_ID = PUBLISHER.PUBLISHER_ID
GROUP BY
    TO_CHAR(INVOICE.ISSUE_DATE, 'YYYY-MM'),
    PUBLISHER.PUBLISHER_NAME
ORDER BY
    TO_CHAR(INVOICE.ISSUE_DATE, 'YYYY-MM'),
    PUBLISHER.PUBLISHER_NAME;

-- 4.b
SELECT
    TO_CHAR(RENTAL.RENTAL_DATE, 'YYYY-MM') AS MONTH_YEAR,
    READER.LAST_NAME,
    COUNT(RENTAL.COPY_ID) AS NUM_BORROWED_COPIES
FROM
    RENTAL_TBL RENTAL
JOIN
    READER_TBL READER ON RENTAL.READER_ID = READER.READER_ID
WHERE
    EXTRACT(YEAR FROM RENTAL.RENTAL_DATE) >= EXTRACT(YEAR FROM SYSDATE) - 5
GROUP BY
    TO_CHAR(RENTAL.RENTAL_DATE, 'YYYY-MM'),
    READER.LAST_NAME
ORDER BY
    TO_CHAR(RENTAL.RENTAL_DATE, 'YYYY-MM'),
    READER.LAST_NAME;

-- 4.c
SELECT
    EXTRACT(YEAR FROM RENTAL.RENTAL_DATE) AS YEAR,
    EMPLOYEE.LAST_NAME,
    COUNT(DISTINCT RENTAL.RENTAL_ID) AS NUM_BORROWINGS,
    COUNT(DISTINCT CASE WHEN RENTAL.RETURN_DATE IS NOT NULL THEN RENTAL.RENTAL_ID END) AS NUM_ACCEPTED_RETURNS
FROM
    RENTAL_TBL RENTAL
JOIN
    EMPLOYEE_TBL EMPLOYEE ON RENTAL.EMPLOYEE_ID_RENT = EMPLOYEE.EMPLOYEE_ID
GROUP BY
    EXTRACT(YEAR FROM RENTAL.RENTAL_DATE),
    EMPLOYEE.LAST_NAME
ORDER BY
    EXTRACT(YEAR FROM RENTAL.RENTAL_DATE),
    EMPLOYEE.LAST_NAME;
